---
- name: install and configure couch cluster
  hosts: servers
  remote_user: ubuntu
  become: yes
  become_user: root

- hosts: myhost
  tasks:
   - name: install git 
     apt: name=git state=present
   
   - name: install python 3
     apt: name=python3 state=present

   - name: install pip
     apt: name=python-pip state=present

   - name: install pip3
     apt: name=python3-pip state=present

   - name: install tweepy
     pip: name=tweepy state=present executable=pip3

   - name: install couchdb
     pip: name=couchdb state=present executable=pip3

   - name: install textblob
     pip: name=textblob state=present executable=pip3

   - name: install numpy
     pip: name=numpy state=present executable=pip3

   - name: install nltk
     pip: name=nltk state=present executable=pip3

   - name: install sklearn
     pip: name=sklearn state=present executable=pip3

   - name: install flask
     pip: name=flask state=present executable=pip3

   - name: clone docker repo into root folder
     git:
        repo: https://github.com/redgeoff/docker-ce-vagrant
        clone: yes
        dest: /root/docker-ce-vagrant

   - name: make directory to save development code
     file: path=/home/ubuntu/cluster-n-cloud-computing state=directory

   - name: clone development code repo into cluster-n-cloud-computing folder
     git:
        repo: https://github.com/freddieMe/cluster-n-cloud-computing
        clone: yes
        dest: /home/ubuntu/cluster-n-cloud-computing


   - name: make directory to nltk words
     file: path=/home/ubuntu/nltk_data state=directory

   - name: copy nltk words
     #copy: src=/home/ubuntu/cluster-n-cloud-computing/ansible/corpora dest=/home/ubuntu/nltk_data remote_src=yes directory_mode=yes
     command: cp -r /home/ubuntu/cluster-n-cloud-computing/ansible/corpora /home/ubuntu/nltk_data/

   - name: update apt cache
     apt:
        update_cache: yes

   - name: change into repository directory and install docker
     shell: "/root/docker-ce-vagrant/docker.sh"

   - name: make directory to save data
     file: path=/home/ubuntu/common state=directory

   - name: install docker-py
     pip: name=docker-py state=present

   - name: run couchdb docker
     docker_container:
        name: couchdb
        image: redgeoff/couchdb
        state: started
        restart_policy: always
        log_options:
          max-size: 100m
        published_ports: "[{% for port in range(9100, 9201) %}'{{port}}:{{port}}'{% if not loop.last %},{% endif %}{% endfor %},'4369:4369','5984:5984','5986:5986']"
        volumes:
          - /home/ubuntu/common:/home/couchdb/common
        env:
            COUCHDB_DATA_DIR: "/home/couchdb/common/data"
            COUCHDB_USER: "admin"
            COUCHDB_HASHED_PASSWORD: "-pbkdf2-b1eb7a68b0778a529c68d30749954e9e430417fb,4da0f8f1d98ce649a9c5a3845241ae24,10"
            COUCHDB_COOKIE: "mycookie"
            COUCHDB_NODE_NAME: "{{ inventory_hostname }}"

   - name: add node source
     shell: "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -"

   - name: install npm
     apt: name={{ item }} update_cache=yes state=latest
     with_items:
        - build-essential
        - nodejs

   - name: install npm in global mode
     npm:
        name:  npm
        global: yes

   - name: install add-cors-to-couchdb module
     npm:
        name: add-cors-to-couchdb
        global: yes

   - name: add cors to couchdb
     shell: "add-cors-to-couchdb http://localhost:5984 -u admin -p admin"

   - name: clone cluster repo
     git:
        repo: https://github.com/redgeoff/redgeoff-couchdb-docker
        clone: yes
        dest: /root/redgeoff-couchdb-docker

   - name: add nodes to cluster
     shell: /root/redgeoff-couchdb-docker/create-cluster.sh admin admin 5984 5986 "{{ item }} {{ inventory_hostname }}"
     with_items: "{{ groups['myhost'] }}"
     when: inventory_hostname == groups['myhost'][0] and inventory_hostname != item



   